name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Debug the directory structure
    - name: Debug repository structure
      run: |
        echo "Working Directory: $(pwd)"
        echo "Contents of $(pwd):"
        ls -R
        echo "Full path for Dockerfile:"
        find . -name Dockerfile

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Build and Push Docker Image
    - name: Build and push Docker image
      run: |
        DOCKERFILE_PATH=$(find . -name Dockerfile)
        CONTEXT_PATH=$(dirname $DOCKERFILE_PATH)
        echo "Dockerfile path: $DOCKERFILE_PATH"
        echo "Context path: $CONTEXT_PATH"
        docker buildx build \
          -f $DOCKERFILE_PATH \
          -t ${{ secrets.DOCKER_USERNAME }}/web:latest \
          $CONTEXT_PATH --push
