name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on a push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Debug repository structure
    - name: Debug repository structure
      run: |
        echo "Current working directory:"
        pwd
        echo "Repository structure:"
        ls -R

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker buildx build \
          -f $GITHUB_WORKSPACE/webprojects/HTMLPaint/Dockerfile \
          -t ${{ secrets.DOCKER_USERNAME }}/web:latest \
          $GITHUB_WORKSPACE/webprojects/HTMLPaint --push

    # Step 6: SSH to EC2 instance and deploy the Docker container
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy Docker container on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@15.206.89.21 <<EOF
        docker pull ${{ secrets.DOCKER_USERNAME }}/web:latest
        docker stop web-container || true
        docker rm web-container || true
        docker run -d --name web-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/web:latest
        EOF
