name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Trigger action on push to main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: List files in the repository to check structure
    - name: List files in the repository
      run: |
        ls -R

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Login to Docker Hub using GitHub secrets
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub secret for Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub secret for Docker Hub password

    # Step 5: Build the Docker image from the HTMLPaint folder  
    - name: Build Docker image
      run: |
        docker build -f $(pwd)/webprojects/HTMLPaint/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/web:latest $(pwd)/webprojects/HTMLPaint

    # Step 6: Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/web:latest

    # Step 7: Set up SSH key to EC2 instance
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # GitHub secret for EC2 SSH key

    # Step 8: SSH to EC2 and Deploy Docker container
    - name: SSH to EC2 and Deploy Docker container
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} "docker pull ${{ secrets.DOCKER_USERNAME }}/web:latest && docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/web:latest"
