name: Deploy to EC2 on Push

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    paths:
      - 'HTMLPaint/**'  # Trigger only if files in HTMLPaint folder change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up SSH key for EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Build Docker image
        run: |
          cd HTMLPaint
          docker build -t suganyamadhan1996/web:latest .

      - name: Push Docker image to DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username suganyamadhan1996--password-stdin
          docker push suganyamadhan1996/web:latest

      - name: SSH to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@15.206.89.21 << 'EOF'
            docker pull suganyamadhan1996/web:latest
            docker stop web || true
            docker rm web || true
            docker run -d -p 80:80 --name web suganyamadhan1996/web:latest
          EOF
