name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger action on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: List files for debugging (optional)
    - name: List files in the workspace
      run: |
        echo "Listing files in the workspace:"
        ls -R

    # Step 3: Build Docker image using the correct relative path
    - name: Build Docker image
      run: |
        echo "Building Docker image from ./webprojects/HTMLPaint/Dockerfile"
        docker buildx build -f webprojects/HTMLPaint/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/web:latest webprojects/HTMLPaint --push

    # Step 4: Push Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/web:latest
