name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main  # Adjust this to match your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t suganyamadhan1996/web:latest .
        docker push suganyamadhan1996/web:latest

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.EC2_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@15.206.89.21 << 'EOF'
          # Stop existing container if running
          docker stop web || true
          docker rm web || true

          # Pull the latest image
          docker pull suganyamadhan1996/web:latest

          # Run the container
          docker run -d --name web -p 80:80 suganyamadhan1996/web:latest
        EOF
